// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/datadog/datadog.go
//
// Generated by this command:
//
//	mockgen -source=pkg/datadog/datadog.go -package mock_datadog -destination pkg/mocks/datadog_mock.go
//

// Package mock_datadog is a generated GoMock package.
package mock_datadog

import (
	reflect "reflect"

	datadog "github.com/zorkian/go-datadog-api"
	gomock "go.uber.org/mock/gomock"
)

// MockClientAPI is a mock of ClientAPI interface.
type MockClientAPI struct {
	ctrl     *gomock.Controller
	recorder *MockClientAPIMockRecorder
	isgomock struct{}
}

// MockClientAPIMockRecorder is the mock recorder for MockClientAPI.
type MockClientAPIMockRecorder struct {
	mock *MockClientAPI
}

// NewMockClientAPI creates a new mock instance.
func NewMockClientAPI(ctrl *gomock.Controller) *MockClientAPI {
	mock := &MockClientAPI{ctrl: ctrl}
	mock.recorder = &MockClientAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientAPI) EXPECT() *MockClientAPIMockRecorder {
	return m.recorder
}

// CreateMonitor mocks base method.
func (m *MockClientAPI) CreateMonitor(arg0 *datadog.Monitor) (*datadog.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMonitor", arg0)
	ret0, _ := ret[0].(*datadog.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMonitor indicates an expected call of CreateMonitor.
func (mr *MockClientAPIMockRecorder) CreateMonitor(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMonitor", reflect.TypeOf((*MockClientAPI)(nil).CreateMonitor), arg0)
}

// DeleteMonitor mocks base method.
func (m *MockClientAPI) DeleteMonitor(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMonitor", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMonitor indicates an expected call of DeleteMonitor.
func (mr *MockClientAPIMockRecorder) DeleteMonitor(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMonitor", reflect.TypeOf((*MockClientAPI)(nil).DeleteMonitor), id)
}

// GetMonitorsByMonitorTags mocks base method.
func (m *MockClientAPI) GetMonitorsByMonitorTags(tags []string) ([]datadog.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonitorsByMonitorTags", tags)
	ret0, _ := ret[0].([]datadog.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonitorsByMonitorTags indicates an expected call of GetMonitorsByMonitorTags.
func (mr *MockClientAPIMockRecorder) GetMonitorsByMonitorTags(tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonitorsByMonitorTags", reflect.TypeOf((*MockClientAPI)(nil).GetMonitorsByMonitorTags), tags)
}

// MuteMonitorScope mocks base method.
func (m *MockClientAPI) MuteMonitorScope(id int, muteMonitorScope *datadog.MuteMonitorScope) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MuteMonitorScope", id, muteMonitorScope)
	ret0, _ := ret[0].(error)
	return ret0
}

// MuteMonitorScope indicates an expected call of MuteMonitorScope.
func (mr *MockClientAPIMockRecorder) MuteMonitorScope(id, muteMonitorScope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MuteMonitorScope", reflect.TypeOf((*MockClientAPI)(nil).MuteMonitorScope), id, muteMonitorScope)
}

// UnmuteMonitor mocks base method.
func (m *MockClientAPI) UnmuteMonitor(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnmuteMonitor", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnmuteMonitor indicates an expected call of UnmuteMonitor.
func (mr *MockClientAPIMockRecorder) UnmuteMonitor(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnmuteMonitor", reflect.TypeOf((*MockClientAPI)(nil).UnmuteMonitor), id)
}

// UpdateMonitor mocks base method.
func (m *MockClientAPI) UpdateMonitor(arg0 *datadog.Monitor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMonitor", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMonitor indicates an expected call of UpdateMonitor.
func (mr *MockClientAPIMockRecorder) UpdateMonitor(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMonitor", reflect.TypeOf((*MockClientAPI)(nil).UpdateMonitor), arg0)
}
